# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256.xci
# IP: The module: 'afifo_16i_16o_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256.xci
# IP: The module: 'afifo_16i_16o_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Temp/HardwareGroup/pengxiaofei/05.FPGA_Projects/hpcs_fpga_dev/hpcs_fpga_dev.srcs/sources_1/ip/afifo_16i_16o_256/afifo_16i_16o_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_16o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
