# ----------------------------------------
# Created on: Tue Dec 26 18:58:25 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L iolhr_dft -L iserdes_e1 -L oserdes_e1 tb_src3cpld usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 8500ns

# ----------------------------------------
