# ----------------------------------------
# Created on: Wed Dec 27 11:19:46 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L iolhr_dft -L iserdes_e1 -L oserdes_e1 tb_src3cpld usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 10us

# ----------------------------------------
