# ----------------------------------------
# Created on: Mon Dec 25 12:42:58 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_10.4/pango_sim_libraries/usim"
vmap  adc "D:/modeltech64_10.4/pango_sim_libraries/adc"
vmap  iolhr_dft "D:/modeltech64_10.4/pango_sim_libraries/iolhr_dft"
vmap  iserdes_e1 "D:/modeltech64_10.4/pango_sim_libraries/iserdes_e1"
vmap  oserdes_e1 "D:/modeltech64_10.4/pango_sim_libraries/oserdes_e1"
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/led_light.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/src3cpld.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart_protocol.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart_recv_nbytes.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart_send_nbytes.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart_rx.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/uart_tx.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/get_signal_edge.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/delay_cy.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/circular_buffer.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/ipcore/clk_pll_0/clk_pll_0.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/tb_src3cpld.v" -work work
vlog   "D:/FPGAProjects/SRC3/IOB_4K_IFC_protocol_git/source/tb_delay_cy.v" -work work

# ----------------------------------------
