# ----------------------------------------
# Created on: Mon Dec 25 12:42:58 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L iolhr_dft -L iserdes_e1 -L oserdes_e1 tb_delay_cy usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1500ns

# ----------------------------------------
